### ISSUE TITLE
Dokument se seznamem požadavků (5 bodů)

### ISSUE THREAD

**Issue by Mikynek** [fix1t/Pacman-game-Java#3]
Ze zadání:

Vytvořte seznam požadavků, které budete v rámci projektu řešit. Požadavky vycházejí ze zadání projektu, upřesňují jejich podobu, příp. je rozšiřují.
- U každého požadavku uveďte:
  - **prioritu** (u požadavku s nižší prioritou nevadí, pokud nebude z důvodu časové tísně realizována, protože nemá vliv na minimální požadavky podle zadání )
  - **stručný popis požadavku**
  - který **člen týmu** je **za požadavek odpovědný**
  - **termín (milestone)**, do kterého by měl být (příp. již byl) požadavek zpracován
- Formát specifikace požadavků
  - PDF dokument v rozsahu do dvou stran A4.
  - Název souboru bude xlogin.pdf, kde xlogin je login vedoucího týmu.
  - Vzor dokumentu pro inspiraci je dostupný dole na stránce.

**Na ukázce to stejně jde vidět úplně nejlíp:** 
[requirements-template.pdf](https://github.com/fix1t/IJA-PACMAN/files/11121761/requirements-template.pdf)

**Comment by Mikynek** [comment]
https://moodle.vut.cz/mod/forum/discuss.php?d=2121 budeme sledovat ještě tenhle thread a kdyžtak by to šlo udělat i víc interaktivně, jak popisuje borec na fóru [Kanban Board]

**Comment by fix1t** [comment]
JJ nice, prípadne github issues
